---
title: "R Notebook"
output: html_notebook
---


```{r}
yA <- c(14.29,19.10,19.09,16.25,15.09,16.61,19.63)
yB <- c(20.06,20.64,18.00,19.56,19.47,19.07,18.38)
yC <- c(20.04,26.23,22.74,24.04,23.37,25.02,23.27)
y = c(yA,yB,yC)
y
```

```{r}
k = 3
n = length(yA)
x0 = rep(1,k*n)
xA = c(rep(1,n), rep(0,n),rep(0,n))
xB = c(rep(0,n), rep(1,n),rep(0,n))
xC = c(rep(0,n), rep(0,n),rep(1,n))
X = cbind(x0,xA,xB,xC)
X
```
```{r}
library(Matrix)
m1 <- matrix(c(2,-1,-1,-1,2,-1,-1,-1,2), nrow = 3, ncol = 3, byrow = TRUE)
rankMatrix(m1)
```

```{r}
XtXi = matrix(rep(0,(k+1)*(k+1)), nrow = k+1)
for(i in 1:k){XtXi[i+1,i+1] = 1/n}
XtXi
```

```{r}
beta = XtXi %*% t(X) %*% y
```

```{r}
SSE = t(y)%*%y - t(beta)%*%t(X)%*%y
```

```{r}
s2 = SSE/(k*(n-1))
```

```{r}
C = matrix(c(0,1,-1,0,0,1,0,-1), nrow = 2, byrow = TRUE)
k = 3
m = k-1
n = length(yA)
n
```
```{r}
Fnum = t(C%*%beta)%*%solve(C%*%XtXi%*%t(C))%*%(C%*%beta)
Fdenom = SSE
F = (Fnum/(k-1))/(Fdenom/(k*(n-1)))
F
```
```{r}
pval = 1 - pf(F, k-1, k*(n-1)) #pf is the cumulative prob of the F dist.
pval
```
We reject since the pvalue is smaller than alpha. 

```{r}
grp = c(rep(1,n), rep(2,n), rep(3,n))
y1 = as.data.frame(cbind(y, factor(grp)))
colnames(y1) = c("y", "grp")
y1$grp = factor(y1$grp)
y1
```
```{r}
y.aov = aov(y~grp, data = y1)
summary(y.aov)


```
SSH is grp, treatments (147.35), Fnum
SSE is Residuals, error (54.97), Fdenum

To check F = 24.13
```{r}
73.67/3.05
```
```{r}
library(mlbench)
data("BostonHousing")
housing = BostonHousing[-4]
housing.full = lm(medv~., data = housing)
housing.full # gives the coefficients
summary(housing.full) # check which coefficients are significant
```

We reject the null hypothesis since p-value < 2.2e-16
