---
title: "R Notebook"
output: html_notebook
---
```{r}
wl = read.csv("2022H2_stonino.csv")
wl.ts = ts(wl)
```

```{r}
library(tseries)
library(forecast)
library(TSA)
library(fGarch)
```

```{r}
plot(wl.ts)
```
```{r}
adf.test(wl.ts)
Box.test(wl.ts)
```
```{r}
acf(wl.ts)
pacf(wl.ts)
```
Test AR(1), AR(2), AR(3), AR(4)
```{r}
Arima(wl.ts, order = c(1,0,0))
Arima(wl.ts, order = c(2,0,0))
Arima(wl.ts, order = c(3,0,0))
Arima(wl.ts, order = c(4,0,0))
```
AR(4) is the best model.

```{r}
ar4 = Arima(wl.ts, order = c(4,0,0))
```

```{r}
plot(forecast(ar4, h = 10))
```
```{r}
res.ar4 = ar4$residuals
tsdiag(ar4)
```

```{r}
y2 = res.ar4^2
Box.test(res.ar4)
Box.test(y2, type = "Ljung")
```
```{r}
acf(y2)
pacf(y2)
```
Test our ARCH(1)

```{r}
arch1 = garchFit(~arma(4,0) + garch(1,0), data = wl.ts)
garch11 = garchFit(~arma(4,0) + garch(1,1), data = wl.ts)
garch22 = garchFit(~arma(4,0) + garch(2,2), data = wl.ts)
arch2 = garchFit(~arma(4,0) + garch(2,0), data = wl.ts)
arch5 = garchFit(~arma(4,0) + garch(5,0), data = wl.ts)
arch7 = garchFit(~arma(4,0) + garch(7,0), data = wl.ts)
```

